package be.school.portal.auth_service.common.utils;

import be.school.portal.auth_service.common.builders.SecurityExceptionFactory;
import be.school.portal.auth_service.common.security.UserPrincipal;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 * Provides centralized and secure access to details of the currently authenticated user.
 *
 * <p>This utility class acts as a lightweight abstraction over Spring Security's {@link
 * org.springframework.security.core.context.SecurityContextHolder}, allowing application components
 * to retrieve authentication and identity information without directly coupling to the underlying
 * security framework.
 *
 * <p>It primarily supports operations for extracting the current user's username or {@link
 * be.school.portal.auth_service.account.domain.entities.UserAccount} instance, assuming the
 * authenticated principal is represented by a {@link
 * be.school.portal.auth_service.common.security.UserPrincipal}.
 *
 * <p>If no authenticated user is present in the current security context, this class throws an
 * {@link org.springframework.security.authentication.AuthenticationCredentialsNotFoundException}
 * generated by {@link be.school.portal.auth_service.common.builders.SecurityExceptionFactory}.
 *
 * <p>This class is declared {@code final} and has a private constructor to enforce
 * non-instantiability, aligning with best practices for utility classes.
 *
 * <h3>Usage Example</h3>
 *
 * <pre>{@code
 * UserAccount currentUser = SecurityContextUtil.getUserAccount();
 * String username = SecurityContextUtil.getUsername();
 * }</pre>
 *
 * <h3>Thread-Safety</h3>
 *
 * <p>This class is thread-safe. All methods rely exclusively on {@link SecurityContextHolder},
 * which uses thread-local storage for isolation.
 *
 * @author Francis Jorell J. Canuto
 */
public final class SecurityContextUtil {

  /** Private constructor to prevent instantiation. */
  private SecurityContextUtil() {}

  /**
   * Retrieves the username of the currently authenticated user from the active {@link
   * org.springframework.security.core.context.SecurityContext}.
   *
   * <p>This method expects the authentication principal to be an instance of {@link
   * be.school.portal.auth_service.common.security.UserPrincipal}. If no valid authentication is
   * found, an exception is raised.
   *
   * @return the username of the authenticated user
   * @throws org.springframework.security.authentication.AuthenticationCredentialsNotFoundException
   *     if no valid authentication exists in the current context
   */
  public static String getUsername() {
    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

    if (authentication == null
        || !authentication.isAuthenticated()
        || !(authentication.getPrincipal() instanceof UserPrincipal userDetails)) {
      throw SecurityExceptionFactory.missingAuth();
    }

    return userDetails.getUsername();
  }
}
