-- public."permission" definition

-- Drop table

-- DROP TABLE public."permission";

CREATE TABLE public."permission" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT idx_permission_name UNIQUE (name),
	CONSTRAINT permission_pkey PRIMARY KEY (id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT idx_role_name UNIQUE (name),
	CONSTRAINT role_pkey PRIMARY KEY (id)
);

-- public.user_account definition

-- Drop table

-- DROP TABLE public.user_account;

CREATE TABLE public.user_account (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(255) NOT NULL,
	status int4 NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT idx_user_username UNIQUE (username),
	CONSTRAINT user_account_pkey PRIMARY KEY (id)
);

-- public.refresh_token definition

-- Drop table

-- DROP TABLE public.refresh_token;

CREATE TABLE public.refresh_token (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	device_info varchar(255) NULL,
	expires_at timestamptz(6) NOT NULL,
	issued_at timestamptz(6) NOT NULL,
	user_id int8 NOT NULL,
	revoked bool NOT NULL,
	CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
);


-- public.refresh_token foreign keys

ALTER TABLE public.refresh_token ADD CONSTRAINT fkonvmn7x6wegib73ehd0gol5nk FOREIGN KEY (user_id) REFERENCES public.user_account(id);

-- public.user_role definition

-- Drop table

-- DROP TABLE public.user_role;

CREATE TABLE public.user_role (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id)
);


-- public.user_role foreign keys

ALTER TABLE public.user_role ADD CONSTRAINT fk7ojmv1m1vrxfl3kvt5bi5ur73 FOREIGN KEY (user_id) REFERENCES public.user_account(id);
ALTER TABLE public.user_role ADD CONSTRAINT fka68196081fvovjhkek5m97n3y FOREIGN KEY (role_id) REFERENCES public."role"(id);


-- public.user_login_audit definition

-- Drop table

-- DROP TABLE public.user_login_audit;

CREATE TABLE public.user_login_audit (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"action" varchar(255) NOT NULL,
	attempted_at timestamptz(6) NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT user_login_audit_action_check CHECK (((action)::text = ANY ((ARRAY['LOGIN_SUCCESS'::character varying, 'LOGIN_FAILED_INVALID_CREDENTIAL'::character varying, 'LOGIN_FAILED_INVALID_STATE'::character varying, 'LOGOUT'::character varying, 'SESSION_EXPIRED'::character varying])::text[]))),
	CONSTRAINT user_login_audit_pkey PRIMARY KEY (id)
);

-- public.role_permission definition

-- Drop table

-- DROP TABLE public.role_permission;

CREATE TABLE public.role_permission (
	role_id int8 NOT NULL,
	permission_id int8 NOT NULL,
	CONSTRAINT role_permission_pkey PRIMARY KEY (role_id, permission_id)
);


-- public.role_permission foreign keys

ALTER TABLE public.role_permission ADD CONSTRAINT fka6jx8n8xkesmjmv6jqug6bg68 FOREIGN KEY (role_id) REFERENCES public."role"(id);
ALTER TABLE public.role_permission ADD CONSTRAINT fkf8yllw1ecvwqy3ehyxawqa1qp FOREIGN KEY (permission_id) REFERENCES public."permission"(id);