name: SonarQube Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Checks
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4️⃣ Build and run tests
      - name: Build with Maven
        run: mvn clean verify

      # 5️⃣ Run SonarQube analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: lelscanuto_be-springboot-auth-service
          organization: lelscanuto
          token: ${{ secrets.SONAR_TOKEN }}
